resources:
  repositories:
    - repository: owasp-zap-scan
      type: github
      endpoint: dastscan
      name: ravindrainduri/owasp-zap-scan
      ref: refs/heads/master

jobs:
- template: owasp-zap-ui-scan-template.yml@owasp-zap-scan
  parameters:
    url: $(ApplicationUrl)
    publishAsTestResults: variables.PublishTestResults
